# Problem 4, Part 2: Random Matrices and Inverses

In [1]:
import numpy as np
np.set_printoptions(precision=4, suppress=True)
np.random.seed(42)

Matrix randomizer

d

In [2]:
M1 = np.random.randint(-10, 11, size=(3, 3))
print("M1 =")
print(M1)

M1 =
[[-4  9  4]
 [ 0 -3 10]
 [-4  8  0]]


Matrix inverse calc

In [3]:
M1_inv = np.linalg.inv(M1)
print("M1 inverse =")
print(M1_inv)

M1 inverse =
[[ 0.9091 -0.3636 -1.1591]
 [ 0.4545 -0.1818 -0.4545]
 [ 0.1364  0.0455 -0.1364]]


Identity matrix calc

In [5]:
print("M1 × M1⁻¹ =")
print(M1 @ M1_inv)

M1 × M1⁻¹ =
[[ 1.  0.  0.]
 [ 0.  1. -0.]
 [-0.  0.  1.]]


# Problem 5: Average, Variance, and Correlation

The dataset for this assignment is available [here](https://drive.google.com/drive/folders/1FV7qofHD_olqygrIjASLQ7k7LTyVSEGG?usp=sharing). The prediction task is to predict the price of a house (column price) given the other features. Please ignore the columns id and date, as well as the categorical column zipcode. File kc_house_data.csv includes all the records in the dataset. You should use the entire dataset for the assignment. You can also find a Word document including the feature description in the same folder. In this problem, we will perform some exploratory data analysis using the house price dataset.

In [ ]:
import pandas as pd
import numpy as np

In [2]:
# Load the data
df = pd.read_csv('kc_house_data.csv')

print(f"Dataset shape: {df.shape[0]} rows, {df.shape[1]} columns")
df.head()

Dataset shape: 21613 rows, 21 columns


id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
0      5650     1.0           0     0  ...      7        1180              0   
1      7242     2.0           0     0  ...      7        2170            400   
2     10000     1.0           0     0  ...      6         770              0   
3      5000     1.0           0     0  ...      7        1050            910   
4      8080     1.0           0     0  ...      8        1680              0   

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1955             0    98178  47.5112 -122.257           1340   
1      1951          1991    98125  47.7210 -122.319           1690   
2      1933             0    98028  47.7379 -122.233           2720   
3      1965             0    98136  47.5208 -122.393           1360   
4      1987             0    98074  47.6168 -122.045           1800   

   sqft_lot15  
0        5650  
1        7639  
2        8062  
3        5000  
4        7503  

[5 rows x 21 columns]

In [3]:
# Features to analyze (excluding id, date, zipcode, and price which is the response)
exclude_cols = ['id', 'date', 'zipcode', 'price']
feature_cols = [col for col in df.columns if col not in exclude_cols]

print(f"Features to analyze ({len(feature_cols)} total):")
print(feature_cols)

Features to analyze (17 total):
['bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade', 'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'lat', 'long', 'sqft_living15', 'sqft_lot15']


---
## Part 1: Compute Statistics for Each Feature

1. For each feature, write code to compute the average value, the min and max values, as well as its variance.
    
    Which features have the lowest and the highest average? Include the feature name and their average values for the features with the
    lowest and highest average.
    
    Which features have the lowest and the highest variance? Include the feature name and their variance values for the features with the
    lowest and highest variance.

In [4]:
# Compute statistics for each feature
stats = pd.DataFrame({
    'Min': df[feature_cols].min(),
    'Max': df[feature_cols].max(),
    'Average (Mean)': df[feature_cols].mean(),
    'Variance': df[feature_cols].var()
})

print("Full Statistics Table:")
stats

Full Statistics Table:


Min           Max  Average (Mean)      Variance
bedrooms          0.0000  3.300000e+01        3.370842  8.650150e-01
bathrooms         0.0000  8.000000e+00        2.114757  5.931513e-01
sqft_living     290.0000  1.354000e+04     2079.899736  8.435337e+05
sqft_lot        520.0000  1.651359e+06    15106.967566  1.715659e+09
floors            1.0000  3.500000e+00        1.494309  2.915880e-01
waterfront        0.0000  1.000000e+00        0.007542  7.485226e-03
view              0.0000  4.000000e+00        0.234303  5.872426e-01
condition         1.0000  5.000000e+00        3.409430  4.234665e-01
grade             1.0000  1.300000e+01        7.656873  1.381703e+00
sqft_above      290.0000  9.410000e+03     1788.390691  6.857347e+05
sqft_basement     0.0000  4.820000e+03      291.509045  1.958727e+05
yr_built       1900.0000  2.015000e+03     1971.005136  8.627973e+02
yr_renovated      0.0000  2.015000e+03       84.402258  1.613462e+05
lat              47.1559  4.777760e+01       47.560053  1.919990e-02
long           -122.5190 -1.213150e+02     -122.213896  1.983262e-02
sqft_living15   399.0000  6.210000e+03     1986.552492  4.697612e+05
sqft_lot15      651.0000  8.712000e+05    12768.455652  7.455182e+08

### Which features have the lowest and highest average?

In [5]:
# Find features with lowest and highest average
min_avg_feature = stats['Average (Mean)'].idxmin()
max_avg_feature = stats['Average (Mean)'].idxmax()
min_avg_value = stats['Average (Mean)'].min()
max_avg_value = stats['Average (Mean)'].max()

print(f"Feature with LOWEST average:  {min_avg_feature} = {min_avg_value:.6f}")
print(f"Feature with HIGHEST average: {max_avg_feature} = {max_avg_value:.6f}")

Feature with LOWEST average:  long = -122.213896
Feature with HIGHEST average: sqft_lot = 15106.967566


### Which features have the lowest and highest variance?

In [6]:
# Find features with lowest and highest variance
min_var_feature = stats['Variance'].idxmin()
max_var_feature = stats['Variance'].idxmax()
min_var_value = stats['Variance'].min()
max_var_value = stats['Variance'].max()

print(f"Feature with LOWEST variance:  {min_var_feature} = {min_var_value:.6f}")
print(f"Feature with HIGHEST variance: {max_var_feature} = {max_var_value:.6f}")

Feature with LOWEST variance:  waterfront = 0.007485
Feature with HIGHEST variance: sqft_lot = 1715658774.175470


---
## Part 2: Correlation Coefficient with the Response

2. Compute the correlation coefficient of each feature with the response. Include a table with the correlation coefficient of each feature with the response. 
Which features are positively correlated (i.e., have positive correlation coefficient) with the response?

Which feature has the highest positive correlation with the response?

In [7]:
# Compute correlation of each feature with price
correlations = df[feature_cols].corrwith(df['price'])

# Create a sorted dataframe for display
corr_df = pd.DataFrame({
    'Feature': correlations.index,
    'Correlation with Price': correlations.values
}).sort_values('Correlation with Price', ascending=False)

print("Correlation Table (sorted by correlation):")
corr_df

Correlation Table (sorted by correlation):


Feature  Correlation with Price
2     sqft_living                0.702035
8           grade                0.667434
9      sqft_above                0.605567
15  sqft_living15                0.585379
1       bathrooms                0.525138
6            view                0.397293
10  sqft_basement                0.323816
0        bedrooms                0.308350
13            lat                0.307003
5      waterfront                0.266369
4          floors                0.256794
12   yr_renovated                0.126434
3        sqft_lot                0.089661
16     sqft_lot15                0.082447
11       yr_built                0.054012
7       condition                0.036362
14           long                0.021626

### Which features are positively correlated with the response?

In [8]:
# Identify positively correlated features
positive_corr = correlations[correlations > 0]

print(f"Features with POSITIVE correlation ({len(positive_corr)} total):")
for feat, corr in positive_corr.sort_values(ascending=False).items():
    print(f"  {feat}: +{corr:.6f}")

Features with POSITIVE correlation (17 total):
  sqft_living: +0.702035
  grade: +0.667434
  sqft_above: +0.605567
  sqft_living15: +0.585379
  bathrooms: +0.525138
  view: +0.397293
  sqft_basement: +0.323816
  bedrooms: +0.308350
  lat: +0.307003
  waterfront: +0.266369
  floors: +0.256794
  yr_renovated: +0.126434
  sqft_lot: +0.089661
  sqft_lot15: +0.082447
  yr_built: +0.054012
  condition: +0.036362
  long: +0.021626


### Which feature has the highest positive correlation with the response?

In [9]:
# Feature with highest positive correlation
max_corr_feature = correlations.idxmax()
max_corr_value = correlations.max()

print(f"Feature with HIGHEST positive correlation: {max_corr_feature} = {max_corr_value:.6f}")

Feature with HIGHEST positive correlation: sqft_living = 0.702035


---
## Part 3: Features with Negative Correlation

Were you able to find any features with a negative correlation coefficient with the response?

In [10]:
# Check for negatively correlated features
negative_corr = correlations[correlations < 0]

if len(negative_corr) > 0:
    print(f"Yes, {len(negative_corr)} feature(s) have NEGATIVE correlation with price:")
    for feat, corr in negative_corr.sort_values().items():
        print(f"  {feat}: {corr:.6f}")
else:
    print("No features with negative correlation were found.")
    print("All 17 features are positively correlated with price.")

No features with negative correlation were found.
All 17 features are positively correlated with price.
